name = "SimulationParameters"
uuid = "32ab26d3-25d6-405d-a295-367385e16093"
authors = ["Orso Meneghini <orso82@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
